"use client";
import React, { useState, useEffect } from "react";
import Link from "next/link";
import { useParams } from "next/navigation";
import "../../landing/landing.css";

const LogoIcon = () => (
  <svg width="28" height="28" viewBox="0 0 28 28" fill="none">
    <rect width="28" height="28" rx="8" fill="#1f2223" />
    <path d="M8 14L14 8L20 14L14 20L8 14Z" fill="#e0ff82" stroke="#e0ff82" strokeWidth="1.5" strokeLinejoin="round" />
    <circle cx="14" cy="14" r="3" fill="#1f2223" />
  </svg>
);
const ArrowLeft = () => <svg width="16" height="16" viewBox="0 0 16 16" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M13 8H3M7 12L3 8l4-4" /></svg>;
const MenuIcon = () => <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><line x1="4" y1="7" x2="20" y2="7"/><line x1="4" y1="12" x2="20" y2="12"/><line x1="4" y1="17" x2="20" y2="17"/></svg>;
const CloseIcon = () => <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/></svg>;
const LinkedInIcon = () => (
  <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
    <path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z" />
    <rect x="2" y="9" width="4" height="12" />
    <circle cx="4" cy="4" r="2" />
  </svg>
);
const XIcon = () => (
  <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
    <path d="M4 4l11.733 16h4.267l-11.733 -16z" />
    <path d="M4 20l6.768 -6.768m2.46 -2.46l6.772 -6.772" />
  </svg>
);
const FacebookIcon = () => (
  <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
    <path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z" />
  </svg>
);

const navLinks = [
  { label: "About", href: "/about" },
  { label: "Feature", href: "/feature" },
  { label: "Pricing", href: "/pricing" },
  { label: "Contact", href: "/contact" },
  { label: "Blog", href: "/blog" },
];

const blogPosts = [
  {
    slug: "announcing-our-2-3m-seed-round-transforming-ozymorlab-work-management",
    title: "Announcing our $2.3M Seed Round to Transform Academic Assessment",
    content: `We are thrilled to announce that OzymorLab has raised a $2.3M Seed round to expand our explainable grading and rubric-grounding engine. The round is led by Y Combinator, with participation from leading institutional partners, academic controllers, and prominent angel investors in education technology.


OzymorLab was started to solve a clear and growing challenge in academic systems: grading load is increasing, yet standard LLM-based solutions lack explainability, security, and integration with classical rubrics. 

### Why Rubric Grounding Matters
Many schools are hesitant to introduce automation into grading due to the risk of hallucination or misalignment with strict institutional rubrics. OzymorLab's core innovation lies in Rubric Grounding—ensuring that every single evaluation point generated by our models is strictly linked to one or more elements of a school's predefined marking scheme.

### What's Next
This funding will allow us to:
* Accelerate development of our multimodal OCR normalizer to support cursive hand-written mathematical calculus and algebra derivations.
* Scale integration support for CANVAS and BLACKBOARD pipelines to allow direct one-click ingestion.
* Expand support for FERPA and SOC-2 Type II audit systems.

We are deeply grateful to our pilot districts and user community. The future of academic evaluation is collaborative, explainable, and secure.`,
    date: "May 24, 2026",
    readTime: "4 min read",
    category: "Company",
    color: "#e0ff82",
    imageUrl: "https://images.unsplash.com/photo-1551836022-d5d88e9218df?q=80&w=600&auto=format&fit=crop",
  },
  {
    slug: "how-rubric-grounding-secures-grading-integrity",
    title: "How Rubric Grounding Secures Grading Integrity in Districts",
    content: `As school districts scale digital assessment, maintaining grading integrity becomes critical. Standard grading tools calculate basic percentages but lack the granular tracking needed for formal grading reviews or audits.

In this article, we break down how OzymorLab uses explainable tracing and groundings to match student response calculations to specific rubric rows. This guarantees that student scores can always be verified and justified with absolute transparency.`,
    date: "May 18, 2026",
    readTime: "6 min read",
    category: "Technology",
    color: "#e0f2fe",
    imageUrl: "https://images.unsplash.com/photo-1427504494785-3a9ca7044f45?q=80&w=600&auto=format&fit=crop",
  },
  {
    slug: "transcribing-cursive-math-derivations-ocr-breakthrough",
    title: "Transcribing Cursive Math Derivations: A Multimodal OCR Breakthrough",
    content: `Handwritten mathematical derivations present a unique challenge for automated OCR systems. Cursive handwriting combined with mathematical syntax requires robust multimodal parsing.

OzymorLab's engineering team has optimized our OCR engine to parse cursive derivations and convert them into structured math equations. This enables clean rubric matching and feedback, saving hours of manual review.`,
    date: "May 12, 2026",
    readTime: "8 min read",
    category: "Engineering",
    color: "#fee2e2",
    imageUrl: "https://images.unsplash.com/photo-1453733190148-c44698c26578?q=80&w=600&auto=format&fit=crop",
  },
  {
    slug: "ferpa-compliance-in-ai-driven-evaluation",
    title: "Navigating FERPA Compliance in AI-Driven Evaluation Workflows",
    content: `Student privacy is paramount. When implementing AI workflows in academic systems, compliance with FERPA regulations is mandatory.

Here, we outline how OzymorLab secures student records, encrypts personal information, and conforms to school district auditing requirements to maintain a secure and compliant learning ecosystem.`,
    date: "April 28, 2026",
    readTime: "5 min read",
    category: "Compliance",
    color: "#fef3c7",
    imageUrl: "https://images.unsplash.com/photo-1450133064473-71024230f91b?q=80&w=600&auto=format&fit=crop",
  }
];

export default function ArticlePage() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [scrolled, setScrolled] = useState(false);
  const params = useParams();

  useEffect(() => {
    const fn = () => setScrolled(window.scrollY > 20);
    window.addEventListener("scroll", fn, { passive: true });
    return () => window.removeEventListener("scroll", fn);
  }, []);

  const post = blogPosts.find(p => p.slug === params.slug) || blogPosts[0];

  return (
    <div className="lp-root">
      {/* ─── NAV ─── */}
      <nav className={`lp-nav ${scrolled ? "lp-nav--scrolled" : ""}`}>
        <div className="lp-nav__inner">
          <Link href="/" className="lp-nav__logo"><LogoIcon /><span>OzymorLab</span></Link>
          <div className="lp-nav__links">
            {navLinks.map(l => <Link key={l.label} href={l.href} className="lp-nav__link">{l.label}</Link>)}
          </div>
          <div className="lp-nav__actions">
            <Link href="/login" className="lp-btn lp-btn--outline">Start Free Pilot</Link>
            <Link href="/login" className="lp-btn lp-btn--primary">Request Demo</Link>
          </div>
          <button className="lp-nav__burger" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle menu">{menuOpen ? <CloseIcon /> : <MenuIcon />}</button>
        </div>
        {menuOpen && (
          <div className="lp-mobile-menu">
            {navLinks.map(l => <Link key={l.label} href={l.href} className="lp-mobile-menu__link" onClick={() => setMenuOpen(false)}>{l.label}</Link>)}
            <div className="lp-mobile-menu__actions">
              <Link href="/login" className="lp-btn lp-btn--outline lp-btn--full">Start Free Pilot</Link>
              <Link href="/login" className="lp-btn lp-btn--primary lp-btn--full">Request Demo</Link>
            </div>
          </div>
        )}
      </nav>

      {/* ═══ ARTICLE DETAIL ═══ */}
      <article style={{ padding: "140px 24px 100px", maxWidth: 800, margin: "0 auto" }}>
        <div style={{ marginBottom: 32 }}>
          <Link href="/blog" className="lp-btn lp-btn--outline" style={{ padding: "6px 12px", borderRadius: 8, display: "inline-flex", gap: 6, fontSize: 13 }}>
            <ArrowLeft /> Back to Blog
          </Link>
        </div>
        <div style={{ display: "flex", gap: 12, alignItems: "center", marginBottom: 16 }}>
          <span className="lp-blog-card__category">{post.category}</span>
          <span className="lp-blog-card__dot" />
          <span className="lp-blog-card__date">{post.date}</span>
          <span className="lp-blog-card__dot" />
          <span className="lp-blog-card__read-time">{post.readTime}</span>
        </div>
        <h1 className="lp-section-title" style={{ fontSize: "clamp(28px, 5vw, 42px)", marginBottom: 24, lineHeight: 1.2 }}>{post.title}</h1>
        
        {/* Banner banner decoration */}
        <div style={{ backgroundImage: `url(${post.imageUrl})`, backgroundSize: "cover", backgroundPosition: "center", height: 350, borderRadius: 16, marginBottom: 40, position: "relative" }}>
          <div style={{ position: "absolute", bottom: 20, right: 20, background: "rgba(255,255,255,0.9)", padding: 8, borderRadius: 8, backdropFilter: "blur(4px)", display: "flex", alignItems: "center", justifyContent: "center" }}>
            <LogoIcon />
          </div>
        </div>

        {/* Content Body */}
        <div className="lp-article-body" style={{ fontSize: 16, lineHeight: 1.8, color: "var(--lp-fg-alt)" }}>
          {post.content.split("\n\n").map((para, i) => {
            if (para.startsWith("### ")) {
              return <h3 key={i} style={{ fontSize: 20, fontWeight: 600, color: "var(--lp-fg)", marginTop: 32, marginBottom: 16 }}>{para.replace("### ", "")}</h3>;
            }
            if (para.startsWith("* ")) {
              return (
                <ul key={i} style={{ margin: "16px 0", paddingLeft: 20 }}>
                  {para.split("\n").map((li, j) => (
                    <li key={j} style={{ marginBottom: 8 }}>{li.replace("* ", "")}</li>
                  ))}
                </ul>
              );
            }
            return <p key={i} style={{ marginBottom: 20 }}>{para}</p>;
          })}
        </div>
      </article>

      {/* ═══ FOOTER ═══ */}
      <footer className="lp-footer">
        <div className="lp-footer__inner">
          <div className="lp-footer__top">
            <div className="lp-footer__brand">
              <div className="lp-footer__logo"><LogoIcon /><span>OzymorLab</span></div>
              <p className="lp-footer__tagline">Join the 40,000+ businesses using OzymorLab, today</p>
              <div className="lp-footer__form">
                <input className="lp-footer__input" placeholder="Get updated" type="email" />
                <button className="lp-btn lp-btn--primary" type="button">Subscribe</button>
              </div>
            </div>
            <div className="lp-footer__columns">
              <div className="lp-footer__col"><h4>Product</h4><Link href="/">Homepage</Link><Link href="/feature">Feature</Link><Link href="/pricing">Pricing</Link><a href="#">Newsletter</a></div>
              <div className="lp-footer__col"><h4>Company</h4><Link href="/about">About</Link><a href="#">Careers <span className="lp-footer__hiring">We&apos;re hiring!</span></a><Link href="/contact">Contact us</Link><a href="#">Privacy</a></div>
              <div className="lp-footer__col"><h4>Resources</h4><Link href="/login">Log in</Link><a href="#">Start here</a><a href="#">Tutorials</a><Link href="/blog">Blog</Link></div>
            </div>
          </div>
          <div className="lp-footer__bottom">
            <p>&copy; {new Date().getFullYear()} OzymorLab. All rights reserved.</p>
            <div className="lp-footer__socials">
              <a href="https://www.linkedin.com/company/118164239" target="_blank" rel="noopener noreferrer" className="lp-footer__social" aria-label="LinkedIn">
                <LinkedInIcon />
              </a>
              <a href="https://x.com" target="_blank" rel="noopener noreferrer" className="lp-footer__social" aria-label="X">
                <XIcon />
              </a>
              <a href="https://facebook.com" target="_blank" rel="noopener noreferrer" className="lp-footer__social" aria-label="Facebook">
                <FacebookIcon />
              </a>
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
}
